create extension if not exists pgcrypto;

create table if not exists public.information_cases (
  id bigint generated by default as identity primary key,
  case_no text not null default '',
  is_done boolean not null default false,
  problem_social_list text not null default '',
  priority text not null default 'Medium',
  status text not null default 'In progress',
  consult_date date,
  deadline date,
  ward_entry_date date,
  sw_name text not null default '',
  patient_name text not null default '',
  intake text not null default 'OPD',
  intake_no text,
  sex text not null default 'Male',
  admit_date date,
  age integer,
  hn text,
  dx text,
  ward text not null default '',
  area text not null default '',
  md_name text not null default '',
  intervention_plan jsonb not null default '[]'::jsonb,
  dc_date date,
  is_dc_done boolean not null default false,
  followup_date date,
  is_fu_done boolean not null default false,
  note text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.monthly_snapshots (
  id bigint generated by default as identity primary key,
  snapshot_month integer not null,
  snapshot_year integer not null,
  snapshot_type text not null,
  owner_name text not null,
  total_cases integer not null default 0,
  payload_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.app_settings (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.allowed_users (
  email text primary key,
  display_name text not null default '',
  role text not null default 'viewer',
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint allowed_users_role_check check (role in ('admin', 'editor', 'viewer'))
);

create index if not exists information_cases_updated_at_idx
  on public.information_cases (updated_at desc, id desc);

create index if not exists information_cases_consult_date_idx
  on public.information_cases (consult_date);

create index if not exists information_cases_sw_name_idx
  on public.information_cases (sw_name);

create index if not exists information_cases_md_name_idx
  on public.information_cases (md_name);

create index if not exists information_cases_ward_idx
  on public.information_cases (ward);

create index if not exists information_cases_area_idx
  on public.information_cases (area);

create index if not exists monthly_snapshots_period_idx
  on public.monthly_snapshots (snapshot_year desc, snapshot_month desc, created_at desc);

create index if not exists monthly_snapshots_owner_idx
  on public.monthly_snapshots (owner_name);

create index if not exists allowed_users_role_idx
  on public.allowed_users (role, is_active);

alter table public.information_cases enable row level security;
alter table public.monthly_snapshots enable row level security;
alter table public.app_settings enable row level security;
alter table public.allowed_users enable row level security;
